### ISSUE TITLE
Req: Have bot monitor /r/WarshipPorn (& possibly /r/WarplanePorn)

### ISSUE THREAD

**Issue by dziban303** [openseadragon/reddit-bot#5]
It'd be great if the bot could monitor/scrape [WarshipPorn](https://WarshipPorn.reddit.com).

_Edit:_ And [WarplanePorn.](https://www.reddit.com/r/WarplanePorn/)

I forked it, made the change to the config file, and submitted a [pull request](https://github.com/openseadragon/reddit-bot/pull/6)

**Comment by iangilman** [comment]
Great idea! Looks like it might be as easy as updating this line:

https://github.com/openseadragon/reddit-bot/blob/master/openseadragonizer-bot.py#L22

Would you be up for writing a pull request for that?

@avandecreme is that all that needs to happen (and then you can deploy it)?

**Comment by dziban303** [comment]
Alright, I did a pull request: https://github.com/openseadragon/reddit-bot/pull/6

I added /r/WarplanePorn too.

**Comment by dziban303** [comment]
Closing

**Comment by avandecreme** [comment]
Thanks for the PR.
I just deployed it and it started doing is thing: https://www.reddit.com/user/openseadragonizer/

**Comment by iangilman** [comment]
I love it when a plan comes together :)
