### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by spixy** [openseadragon/reddit-bot#7]
[https://www.reddit.com/r/MapPorn/comments/5ms5gg/very_detailed_ethnic_map_of_the_balkans_from_1992/dc5w26c/](https://www.reddit.com/r/MapPorn/comments/5ms5gg/very_detailed_ethnic_map_of_the_balkans_from_1992/dc5w26c/)

**Comment by avandecreme** [comment]
Thanks for reporting. I think the issue come from the URL parameters in the image URL.

**Comment by iangilman** [comment]
@avandecreme Would you say this is an error with OSD or with the OpenSeadragonizer?

**Comment by avandecreme** [comment]
It is an OpenSeadragonizer error.
The URL should be encoded with encodeURIComponent.

Here is a working link: https://openseadragon.github.io/openseadragonizer/?img=https%3A%2F%2Fi.redditmedia.com%2F0w0l6WxHeddaMmrJZlNbsUzaRo10k8GCoUD6sEtwiOw.gif%3Ffm%3Djpg%26s%3Dac2f7b9d22ef37ec9b8d911f512dafcc

**Comment by avandecreme** [comment]
Fixed and deployed!

**Comment by iangilman** [comment]
Awesome :)
